# Generated by Django 6.1.2 on 2026-10-07 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataRep', '0003_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='dataRep.classsection'),
        ),
    ]
