# Generated by Django 6.1.2 on 2026-10-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataRep', '0005_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='school_name',
        ),
    ]
