# Generated by Django 6.1.2 on 2026-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataRep', '0006_remove_teacherprofile_school_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=20)),
                ('percentage', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
