# Generated by Django 6.1.2 on 2026-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataRep', '0007_guestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='join_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
