# Generated by Django 6.1.2 on 2026-10-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataRep', '0008_classsection_join_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=25)),
                ('percentage', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataRep.studentprofile')),
            ],
        ),
    ]
